const CLUE_BANK = {
  "APPLE": { en: "A common round red or green fruit", zh: "苹果" },
  "BREAD": { en: "A basic food made from flour and water", zh: "面包" },
  "CLOUD": { en: "A white or gray mass in the sky", zh: "云" },
  "DREAM": { en: "Images or thoughts during sleep", zh: "梦" },
  "EQUAL": { en: "The same in quantity, size, or value", zh: "平等/相等" },
  "FLAME": { en: "The hot, bright part of a fire", zh: "火焰" },
  "GRASS": { en: "Green plants that cover the ground", zh: "草" },
  "HEART": { en: "The organ that pumps blood", zh: "心脏" },
  "INDEX": { en: "An alphabetical list of names or topics", zh: "索引" },
  "JUICE": { en: "The liquid from fruit or vegetables", zh: "果汁" },
  "KNIFE": { en: "A tool used for cutting", zh: "小刀" },
  "LIGHT": { en: "Something that makes things visible", zh: "光" },
  "MONEY": { en: "Coins or notes used to buy things", zh: "钱" },
  "NIGHT": { en: "The time when it is dark outside", zh: "夜晚" },
  "OCEAN": { en: "A very large area of salt water", zh: "海洋" },
  "PIANO": { en: "A large musical instrument with keys", zh: "钢琴" },
  "QUEEN": { en: "A female ruler of a country", zh: "女王" },
  "RADIO": { en: "A device for listening to broadcasts", zh: "收音机" },
  "SMILE": { en: "A happy expression on the face", zh: "微笑" },
  "TABLE": { en: "Furniture with a flat top and legs", zh: "桌子" },
  "UNDER": { en: "In a lower position than something", zh: "在...下面" },
  "VOICE": { en: "The sound made when speaking", zh: "声音" },
  "WATER": { en: "A clear liquid used for drinking", zh: "水" },
  "YOUTH": { en: "The period of being young", zh: "青春" },
  "ZEBRA": { en: "An animal with black and white stripes", zh: "斑马" },
  "ADULT": { en: "A person who is fully grown", zh: "成年人" },
  "BASIC": { en: "Simple or most important", zh: "基础" },
  "CHAIR": { en: "A piece of furniture for sitting", zh: "椅子" },
  "DANCE": { en: "To move your body to music", zh: "跳舞" },
  "EARTH": { en: "The planet we live on", zh: "地球" },
  "FIELD": { en: "An area of open land", zh: "田野" },
  "GHOST": { en: "The spirit of a dead person", zh: "鬼" },
  "HELLO": { en: "A common greeting", zh: "你好" },
  "IMAGE": { en: "A picture or reflection", zh: "图像" },
  "JOKER": { en: "Someone who likes to tell jokes", zh: "小丑" },
  "LEMON": { en: "A sour yellow fruit", zh: "柠檬" },
  "MOUSE": { en: "A small furry animal", zh: "老鼠" },
  "NORTH": { en: "The opposite of south", zh: "北方" },
  "PAPER": { en: "Material used for writing or printing", zh: "纸" },
  "QUIET": { en: "Making very little noise", zh: "安静" },
  "RIVER": { en: "A large natural stream of water", zh: "河流" },
  "STORM": { en: "Very bad weather with rain or wind", zh: "暴风雨" },
  "TIGER": { en: "A large orange and black cat", zh: "老虎" },
  "UNION": { en: "The act of joining together", zh: "联盟" },
  "VALVE": { en: "A device that controls flow", zh: "阀门" },
  "WORLD": { en: "The earth and everything on it", zh: "世界" },
  "XENON": { en: "A heavy colorless gas", zh: "氙气" },
  "YACHT": { en: "A large expensive boat", zh: "游艇" },
  "ZONAL": { en: "Relating to a specific area or zone", zh: "地带的" },
  "ACUTE": { en: "Very sharp or severe", zh: "剧烈的" }
};

module.exports = { CLUE_BANK };
